### ISSUE TITLE
Замечания @sasa2002sasha

### ISSUE THREAD

**Issue by ananasn** [sasa2002sasha/lab3#1]
Несколько замечаний:
* А зачем вы вот это делаете:
```python3
with open('test', 'rb') as file_bmp:
    with open('chart.bmp', 'wb') as picture:
        bmp_internals = file_bmp.read()
        picture.write(bmp_internals)
```

Можно же было сразу в 4 строке вашей программы просто указать расширение bmp
```python3
with open ('test.bmp', 'wb') as file_bmp:
```
Или в этом есть какой-то особый смысл?

* Блочные комментарии лучше писать до кода, а не после (https://www.python.org/dev/peps/pep-0008/#block-comments)

* Еще раз посмотрите как выставляются пробелы в математических выражениях, и поменяйте там, где неправильно (https://www.python.org/dev/peps/pep-0008/#other-recommendations)

* У вас шаг рассчитывается на каждом цикле итерации ` math.pi / 2500`, сделайте константу в начале программы

* Вот эту константу `-255/256` тоже назвать и пояснить в комментарии, что это такое

**Comment by Jyxerr** [comment]
Поправил.
У файла "test" не было смысла.)
